### ISSUE TITLE
Make a skelton

### ISSUE THREAD

**Issue by komunamu** [komunamu/calculator#1]
To start the project we have to make a Skelton.

-Main() method

**Comment by nccheckcashing** [comment]
It will be great to make each function such as add(int a, int b), sub(int a, int b)....

**Comment by komunamu** [comment]
@nccheckcashing  That is good idea!

here is a sample ui

![image](https://cloud.githubusercontent.com/assets/2301552/14211354/99234adc-f7fb-11e5-934a-81e6b0475f8c.png)
